// <auto-generated />
using System;
using Incidentes.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Incidentes.Datos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210927004257_carga_inicial")]
    partial class carga_inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesarrolladorProyecto", b =>
                {
                    b.Property<int>("DesarrolladoresId")
                        .HasColumnType("int");

                    b.Property<int>("proyectosId")
                        .HasColumnType("int");

                    b.HasKey("DesarrolladoresId", "proyectosId");

                    b.HasIndex("proyectosId");

                    b.ToTable("DesarrolladorProyecto");
                });

            modelBuilder.Entity("Incidentes.Dominio.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DesarrolladorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoIncidente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProyectoId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("Incidentes.Dominio.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Incidentes.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasFilter("[NombreUsuario] IS NOT NULL");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("ProyectoTester", b =>
                {
                    b.Property<int>("TestersId")
                        .HasColumnType("int");

                    b.Property<int>("proyectosId")
                        .HasColumnType("int");

                    b.HasKey("TestersId", "proyectosId");

                    b.HasIndex("proyectosId");

                    b.ToTable("ProyectoTester");
                });

            modelBuilder.Entity("Incidentes.Dominio.Desarrollador", b =>
                {
                    b.HasBaseType("Incidentes.Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Desarrollador");
                });

            modelBuilder.Entity("Incidentes.Dominio.Tester", b =>
                {
                    b.HasBaseType("Incidentes.Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Tester");
                });

            modelBuilder.Entity("DesarrolladorProyecto", b =>
                {
                    b.HasOne("Incidentes.Dominio.Desarrollador", null)
                        .WithMany()
                        .HasForeignKey("DesarrolladoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Incidentes.Dominio.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("proyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Incidentes.Dominio.Incidente", b =>
                {
                    b.HasOne("Incidentes.Dominio.Proyecto", null)
                        .WithMany("Incidentes")
                        .HasForeignKey("ProyectoId");
                });

            modelBuilder.Entity("ProyectoTester", b =>
                {
                    b.HasOne("Incidentes.Dominio.Tester", null)
                        .WithMany()
                        .HasForeignKey("TestersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Incidentes.Dominio.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("proyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Incidentes.Dominio.Proyecto", b =>
                {
                    b.Navigation("Incidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
